name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade --no-build-isolation -r  requirements.txt
          python -m pip install -U sphinx
          python -m pip install pydata-sphinx-theme
          python -m pip install sphinx_gallery
          python -m pip install sphinx-prompt
          python -m pip install numpydoc
          python -m pip install -e .

      - name: Check installation
        run: |
          which python
          python -c "import peerannot"

      - name: Sphinx build
        run: |
          cd docs
          make clean
          make html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true

